### ISSUE TITLE
Means we can return a serialized function?

### ISSUE THREAD

**Issue by linonetwo** [tjmehta/graphql-function#2]
What does it mean? Or if we just use this field as a remote function, type should be function's return type, not Function type.

Confused.

**Comment by tjmehta** [comment]
Allows a function to be used as a graphql type. For example, you can use a function as a graphql query input (passing a function from client to the server). Another example, you can return function from server to client.

**Comment by tjmehta** [comment]
Note: the function will be serialized to a string and then parsed on the server using eval (so the function must not use parent scope).

**Comment by tjmehta** [comment]
And also return a function from server to client.

**Comment by linonetwo** [comment]
Wow, that is interesting. I will think of some use cases...
